name: pulse-simple-recorder
base: core24
version: '0.1'
summary: PulseAudio recording demo
description: |
  Uses the simple API to record sounds from the default microphone

confinement: strict
grade: stable

apps:
  record:
    command: bin/record
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/../pulse/native
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$SNAP/usr/lib/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    plugs:
      - audio-playback
      - audio-record
      - pulseaudio

parts:
  record:
    plugin: dump
    source: .
    build-packages:
      - gcc
      - libpulse-dev
    stage-packages:
      - libpulse0
    override-build: |
      ./build.sh
      install -D -m755 record $SNAPCRAFT_PART_INSTALL/bin/record

